# fly.toml app configuration file generated for theraverse-agent-web on 2026-02-13T17:23:19+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'theraverse-agent-web'
primary_region = 'sin'

[build]
  [build.args]
    NEXT_PUBLIC_SUPABASE_URL = "https://lwhfjwkfkvmaqblyphij.supabase.co"
    NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx3aGZqd2tma3ZtYXFibHlwaGlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE5MjgxMTcsImV4cCI6MjA4NzUwNDExN30.C-SIvrLOCJtJmKAyBuGwvf0_UtAcl-IPpY9__nGYa4w"

[env]
  NEXT_TELEMETRY_DISABLED = '1'
  NODE_ENV = 'production'

[http_service]
  internal_port = 3026
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
